### ISSUE TITLE
Fix Redis configuration "examples"

### ISSUE THREAD

**Issue by alex-ikse** [hashicorp/terraform-enterprise-helm#36]
https://github.com/hashicorp/terraform-enterprise-helm/blob/7ac92bcfdb13c69cd574c15614c60f09f0cdb023/env-config.yaml#L27

https://github.com/hashicorp/terraform-enterprise-helm/blob/7ac92bcfdb13c69cd574c15614c60f09f0cdb023/values.yaml#L190

Should be `TFE_REDIS_HOST`, `TFE_REDIS_USER`, `TFE_REDIS_PASSWORD`, `TFE_REDIS_USE_AUTH`, `TFE_REDIS_USE_TLS` : https://developer.hashicorp.com/terraform/enterprise/flexible-deployments-beta/install/configuration#redis-settings

**Comment by kosyfrances** [comment]
Fixed in https://github.com/hashicorp/terraform-enterprise-helm/pull/39
