### ISSUE TITLE
ServiceAccount annotations

### ISSUE THREAD

**Issue by take-five** [hashicorp/terraform-enterprise-helm#44]
Hi

Can you please add an ability to set annotations for the ServiceAccount resource? This will allow us to use [IAM roles for service accounts](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) on AWS EKS.

Thanks!

**Comment by kosyfrances** [comment]
Resolved in https://github.com/hashicorp/terraform-enterprise-helm/pull/45
