### ISSUE TITLE
Adding nodeSelector to jobs

### ISSUE THREAD

**Issue by alldoami** [hashicorp/terraform-enterprise-helm#60]
We'd like to add `nodeSelector` to the config for the jobs that get spun up. Is that possible? We'd like to specify `beta.kubernetes.io/arch` under `nodeSelector` because our clusters have mixed architectures. 

cc @jakeyheath

**Comment by felixskaiser** [comment]
In the same sense, `tolerations` and `affinity` would also be great specs to add to jobs generated for executing runs

**Comment by felixskaiser** [comment]
Probably closed by https://github.com/hashicorp/terraform-enterprise-helm/pull/65

**Comment by kosyfrances** [comment]
Hi @alldoami, I'll be closing this issue because it has been resolved by https://github.com/hashicorp/terraform-enterprise-helm/pull/65.
